---
- import_tasks: install.yml

- name: configure users
  include_tasks: configure-groups.yml
  when: "users is defined and users not in ([], None, '', omit)"

- name: configure single node addons
  include_tasks: addons.yml
  when: not microk8s_enable_HA

- name: configure High Availability
  include_tasks: configure-HA.yml
  when: "microk8s_enable_HA"

# disable it at the moment as it is broken 
# - name: configure workers
#   include_tasks: configure-WORKERS.yml
#   when: "groups[microk8s_group_WORKERS]|length>0"
