---
- import_tasks: install.yml

- name: configure users
  include_tasks: configure-groups.yml
  when: "users is defined and users not in ([], None, '', omit)"

- name: configure single node addons
  include_tasks: addons.yml
  when: not microk8s_enable_HA

- name: configure High Availability
  include_tasks: configure-HA.yml
  when: "microk8s_enable_HA"
